### PR TITLE
Move RPATH and install path generation earlier in workflow

### PR DESCRIPTION
**Pull request by zachcran**
**Is this pull request associated with an issue(s)?**
Not that I am aware of. The issue is summarized by @ryanmrichard's comment in ParallelZone [PR 124](https://github.com/NWChemEx/ParallelZone/pull/124).

**Description**
Currently, installation RPATH information is mainly set during the `cmaize_add_package()` call, which is typically placed at the end of a `CMakeLists.txt` file. This means that if that information is needed to create further targets, that code must also come after the `cmaize_add_package()` call. To avoid needing to reorganize CMakeLists.txt files that exist and expose too many implementation details by enforcing this somewhat unintuitive ordering, this PR moves install path and RPATH information to be set in the corresponding `cmaize_find_or_build_dependency()` or `cmaize_add_library()` calls for a target. This allows the installation path and RPATH information to be accessed directly after these function calls create the targets.

This refactor does remove some of the certainty that was guaranteed by setting RPATH information in `cmaize_add_package()`. During the `cmaize_add_package()` call, the user provides the package name as the only required argument, cementing the name of the package that the targets will be installed under. By setting installation path and RPATH information prior to the `cmaize_add_package()` call, we can no longer guarantee the package name when generating the installation paths and RPATH. To solve this, the package name can be specified when defining each dependency and target. If no package name is provided, then we assume that the installation package name will be the same as the project. It will be the burden of the user to ensure that matching package names are provided when defining dependency and project targets, as well as when defining installation packages.

**TODOs**
- [ ] Provide `PACKAGE_NAME` kwarg for `cmaize_find_or_build_dependency()`, `cmaize_add_library()`, and `cmaize_add_executable()`.

### CODE REVIEW

**Comment by zachcran** [comment]
@ryanmrichard Will you test if this works on your machine with PluginPlay?

**Comment by ryanmrichard** [comment]
@zachcran it looks like the master branch of PluginPlay works with this PR! My test also relied on the master branch of `NWXCMake` which includes some RPATH hackery. I'm going to now try without that hackery.

**Comment by ryanmrichard** [comment]
That looks like it worked too!!!

**Comment by ryanmrichard** [comment]
Regarding the name thing in the description. I think you should use the name of the project and not allow users to overwrite that. By adding the target to the project (which is what `find_or_build` does) that's what they are asking for.

**Review by ryanmrichard — APPROVED** [review]

**Pull request merged**
